services:
  - type: web
    name: migrateiq-frontend
    env: node
    buildCommand: npm install && npm run build
    staticPublishPath: "./dist"
    envVars:
      - key: NODE_VERSION
        value: 18.x
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
    headers:
      - path: "/*"
        name: "Content-Security-Policy"
        value: |
          default-src 'self';
          script-src 'self' 'unsafe-inline' 'unsafe-eval' https://js.stripe.com;
          style-src 'self' 'unsafe-inline';
          img-src 'self' data: blob: https:;
          font-src 'self' data:;
          connect-src 'self' https://api.migrateiq.com ws: wss:;
          frame-src 'self' https://js.stripe.com https://www.paypal.com https://www.sandbox.paypal.com;
      - path: "/*"
        name: "X-Content-Type-Options"
        value: "nosniff"
      - path: "/*"
        name: "X-Frame-Options"
        value: "DENY"
      - path: "/*"
        name: "Referrer-Policy"
        value: "strict-origin-when-cross-origin"
      - path: "/assets/*"
        name: "Cache-Control"
        value: "public, max-age=31536000, immutable"
      - path: "/static/*"
        name: "Cache-Control"
        value: "public, max-age=31536000, immutable"
